apiVersion: alfresco.community.com/v1
kind: Alfresco
metadata:
    name: alfresco-community
    namespace: default
spec:
    postgres:
        name: postgres-db
        replicas: 1
        image: postgres:14.4
        resources:
            limits:
                memory: "512Mi"
                cpu: "500m"
            requests:
                memory: "256Mi"
                cpu: "250m"
        environment:
            POSTGRES_PASSWORD: alfresco
            POSTGRES_USER: alfresco
            POSTGRES_DB: alfresco
        ports:
            - "5432:5432"
    activemq:
        name: activemq-broker
        replicas: 1
        image: alfresco/alfresco-activemq:5.18-jre17-rockylinux8
        resources:
            limits:
                memory: "1Gi"
                cpu: "1"
            requests:
                memory: "512Mi"
                cpu: "500m"
        ports:
            - "8161:8161"
            - "5672:5672"
            - "61616:61616"
            - "61613:61613"
    alfresco:
        name: alfresco-content
        replicas: 1
        image: docker.io/alfresco/alfresco-content-repository-community:23.4.1
        resources:
            limits:
                memory: "1900Mi"
                cpu: "2"
            requests:
                memory: "1024Mi"
                cpu: "1"
        environment:
            JAVA_TOOL_OPTIONS: >-
                -Dencryption.keystore.type=JCEKS
                -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
                -Dencryption.keyAlgorithm=DESede
                -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
                -Dmetadata-keystore.password=mp6yc0UD9e
                -Dmetadata-keystore.aliases=metadata
                -Dmetadata-keystore.metadata.password=oKIWzVdEdA
                -Dmetadata-keystore.metadata.algorithm=DESede
            JAVA_OPTS: >-
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=alfresco3
                -Ddb.url=jdbc:postgresql://postgres-db:5432/alfresco
                -Dsolr.host=solr6
                -Dsolr.port=8983
                -Dsolr.http.connection.timeout=1000
                -Dsolr.secureComms=secret
                -Dsolr.sharedSecret=secret
                -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6
                -Dshare.host=localhost
                -Dshare.port=8080
                -Dalfresco.host=localhost
                -Dalfresco.port=8080
                -Dcsrf.filter.enabled=false
                -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
                -Dmessaging.broker.url="failover:(nio://activemq-broker:61616)?timeout=3000&jms.useCompression=true"
                -Ddeployment.method=DOCKER_COMPOSE
                -DlocalTransform.core-aio.url=http://transform-core-aio:8090/
                -XX:MinRAMPercentage=50
                -XX:MaxRAMPercentage=80
        ports:
            - "8080:8080"