apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alfresco-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "hostpath"
  resources:
    requests:
      storage: 10Gi