apiVersion: apps/v1
kind: Deployment
metadata:
  name: alfresco-community-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alfresco-community-operator
  template:
    metadata:
      labels:
        app: alfresco-community-operator
    spec:
      serviceAccountName: alfresco-operator-sa
      containers:
        - name: operator
          image: cparedesrou/operator-crd-alfresco:2.5
          env:
            - name: KUBERNETES_SERVICE_HOST
              value: "kubernetes.default.svc"
            - name: KUBERNETES_SERVICE_PORT
              value: "443"
---              
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: alfrescos.alfresco.community.com
spec:
  group: alfresco.community.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              additionalProperties:
                type: object
                properties:
                  name:
                    type: string
                  replicas:
                    type: integer
                  image:
                    type: string
                  resources:
                    type: object
                    properties:
                      limits:
                        type: object
                        properties:
                          memory:
                            type: string
                          cpu:
                            type: string
                      requests:
                        type: object
                        properties:
                          memory:
                            type: string
                          cpu:
                            type: string
                  environment:
                    type: object
                    additionalProperties:
                      type: string
                  command:
                    type: array
                    items:
                      type: string
                  ports:
                    type: array
                    items:
                      type: string
                  service_type:
                    type: string
                  readinessProbe:
                    type: object
                    properties:
                      httpGet:
                        type: object
                        properties:
                          path:
                            type: string
                          port:
                            type: integer
                      exec:
                        type: object
                        properties:
                          command:
                            type: array
                            items:
                              type: string
                      tcpSocket:
                        type: object
                        properties:
                          port:
                            type: integer
                      initialDelaySeconds:
                        type: integer
                      periodSeconds:
                        type: integer
                      failureThreshold:
                        type: integer
                      timeoutSeconds:
                        type: integer
                      successThreshold:
                        type: integer
                  livenessProbe:
                    type: object
                    properties:
                      httpGet:
                        type: object
                        properties:
                          path:
                            type: string
                          port:
                            type: integer
                      exec:
                        type: object
                        properties:
                          command:
                            type: array
                            items:
                              type: string
                      tcpSocket:
                        type: object
                        properties:
                          port:
                            type: integer
                      initialDelaySeconds:
                        type: integer
                      periodSeconds:
                        type: integer
                      failureThreshold:
                        type: integer
                      timeoutSeconds:
                        type: integer
                      successThreshold:
                        type: integer
  scope: Namespaced
  names:
    plural: alfrescos
    singular: alfresco
    kind: Alfresco
    shortNames:
      - alf
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alfresco-operator-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alfresco-operator-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: alfresco-operator-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
   